name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: 
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        echo "Fin de login"

    - name: Build Docker Image #"construir imagen"
      run: 
        docker build --tag joselqv202/docker-graphql:1.0.2 .
    - name: push Docker Image #"subir la imagen"
      run: 
        docker push joselqv202/docker-graphql:1.0.2

      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
